app = "TNT_volunteers"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "uv run python -m flask --app app:create_app db upgrade"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
