"""add store collection days and shift indexes

Revision ID: aa05721dfca4
Revises: 5765724a86af
Create Date: 2026-03-02 09:33:44.626893

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "aa05721dfca4"
down_revision = "5765724a86af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shift", schema=None) as batch_op:
        batch_op.create_index(
            "ix_shift_date_store_vol",
            ["date", "store_id", "volunteer_id"],
            unique=False,
        )
        batch_op.create_unique_constraint("uq_shift_date_store", ["date", "store_id"])

    with op.batch_alter_table("store", schema=None) as batch_op:
        batch_op.add_column(sa.Column("collects_monday", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("collects_tuesday", sa.Boolean(), nullable=False))
        batch_op.add_column(
            sa.Column("collects_wednesday", sa.Boolean(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("collects_thursday", sa.Boolean(), nullable=False)
        )
        batch_op.add_column(sa.Column("collects_friday", sa.Boolean(), nullable=False))
        batch_op.add_column(
            sa.Column("collects_saturday", sa.Boolean(), nullable=False)
        )
        batch_op.add_column(sa.Column("collects_sunday", sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("store", schema=None) as batch_op:
        batch_op.drop_column("collects_sunday")
        batch_op.drop_column("collects_saturday")
        batch_op.drop_column("collects_friday")
        batch_op.drop_column("collects_thursday")
        batch_op.drop_column("collects_wednesday")
        batch_op.drop_column("collects_tuesday")
        batch_op.drop_column("collects_monday")

    with op.batch_alter_table("shift", schema=None) as batch_op:
        batch_op.drop_constraint("uq_shift_date_store", type_="unique")
        batch_op.drop_index("ix_shift_date_store_vol")

    # ### end Alembic commands ###
